Repository bepitome/basic-auth, pull requests merged in 2022-07, with the labels that each got.

#21 Add code of conduct 1
  CODE_OF_CONDUCT.md
  package-lock.json
  package.json
Labels: documentation

#23 Create LICENSE
  LICENSE
Labels: documentation

#24 Develop
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  mongo_seed/accounts.json
  restAPI/controllers/controller_user.js
  restAPI/routes/route_user.js
Labels: enhancement

#25 review fixes for pr-20
  LICENSE
  package-lock.json
  package.json
  restAPI/controllers/controller_auth.js
  restAPI/routes/route_auth.js
  server.js
Labels: api

#20 add user login api
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  package-lock.json
  package.json
Labels: api

#26 Feature/validate token
  README.md
  install.sh
  restAPI/controllers/controller_auth.js
  server.js
Labels: api, fixes

#27 Merge master into develop
  README.md
  install.sh
  package-lock.json
  package.json
  restAPI/controllers/controller_auth.js
  restAPI/routes/route_auth.js
  server.js
Labels: documentation, enhancement, api, fixes

#28 added status code & limit auth validation for users route
  restAPI/controllers/controller_user.js
  server.js
Labels: enhancement, fixes

#29 updated readme & added postman collection
  README.md
  basic-auth-postman-collection.json
Labels: documentation

#31 Merge branch 'hotfix/db-instance'
  mongo_conn_native.js
  server.js
Labels: fixes

#37 switched to run dev script in gh action
  .github/workflows/on-pull-request.yml
Labels: ci/cd

#39 release v0.1.3-beta
  .eslintrc.js
  .eslintrc.json
  .github/workflows/on-pull-request.yml
  .husky/pre-commit
  Dockerfile
  Makefile
  README.md
  install.sh
  mongo_conn_native.js
  package-lock.json
  package.json
  public/constant.js
  restAPI/controllers/controller_auth.js
  restAPI/controllers/controller_user.js
  restAPI/routes/route_user.js
Labels: ci/cd, enhancement

#40 Docs readme
  README.md
Labels: documentation

#41 update readme
  README.md
Labels: documentation

#46 Hotfix/npm ci
  Dockerfile
  README.md
  docker-compose.yaml
  package-lock.json
  package.json
Labels: docker

#47 hotfix/npm-ci
  Dockerfile
  docker-compose.yaml
  package-lock.json
  package.json
Labels: docker

#49 Dependabot/npm and yarn/eslint 8.20.0
  package-lock.json
  package.json
Labels: dependencies

#52 [Docs] update readme
  .feature
  README.md
  restAPI/controllers/controller_auth.js
  server.js
Labels: documentation, enhancement

#53 Challenge modification & invalid response bug fix
  .feature
  README.md
  restAPI/controllers/controller_auth.js
  server.js
Labels: documentation, fixes
